name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PUNK_ENV: test
      COVERALLS_REPO_TOKEN: "${{secrets.COVERALLS_REPO_TOKEN}}"

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6.6
        bundler-cache: true
    - name: Lint files
      run: bundle exec rubocop
    - name: Run specs
      run: bundle exec rspec
